"""
scan_bugs_auto.py — Auto-generated static bug patterns.

Generated by the self-improvement loop in run_autonomous_fix.py.
Each function below was created after a bug escaped the main scanner.
Do not edit manually — append via scan_bugs.learn_from_fix().
"""
import ast
from pathlib import Path
from typing import List

_AUTO_PATTERNS: list = []  # Populated below


# Added 2026-04-17 — caught after fixing: missing_validation in tools/execution_engine.py:554
def _auto_check_001(source: str, tree: ast.AST, filepath: pathlib.Path) -> list[dict]:
    """
    A11: Payment method used without validating required credential field.
    Detects if-blocks that check a payment_method string ('wallet', 'stripe_pi', etc.)
    and perform a charge/debit action, but have no guard that the corresponding
    credential field (wallet_id, payment_intent_id, etc.) is truthy before the block.
    """
    import ast as _ast

    PAYMENT_METHOD_CREDENTIALS = {
        "wallet": ["wallet_id"],
        "stripe_pi": ["payment_intent_id"],
        "stripe": ["payment_intent_id", "stripe_token"],
        "paypal": ["paypal_token", "paypal_order_id"],
    }

    CHARGE_INDICATORS = {
        "charge", "debit", "capture", "pay", "payment", "transact",
        "wallet_charge", "stripe_charge", "process_payment",
    }

    findings = []

    class PaymentMethodVisitor(_ast.NodeVisitor):
        def __init__(self):
            self.issues = []

        def _node_calls_charge(self, node: _ast.AST) -> bool:
            for child in _ast.walk(node):
                if isinstance(child, _ast.Call):
                    func = child.func
                    name = ""
                    if isinstance(func, _ast.Attribute):
                        name = func.attr
                    elif isinstance(func, _ast.Name):
                        name = func.id
                    if any(ind in name.lower() for ind in CHARGE_INDICATORS):
                        return True
            return False

        def _extract_payment_method_literal(self, test: _ast.AST) -> str | None:
            """Return the payment method string from a comparison like x == 'wallet'."""
            if isinstance(test, _ast.Compare):
                comparators = test.comparators
                if len(comparators) == 1 and isinstance(comparators[0], _ast.Constant):
                    val = comparators[0].value
                    if isinstance(val, str) and val in PAYMENT_METHOD_CREDENTIALS:
                        return val
                if isinstance(test.left, _ast.Constant):
                    val = test.left.value
                    if isinstance(val, str) and val in PAYMENT_METHOD_CREDENTIALS:
                        return val
            return None

        def _body_guards_credential(self, body: list, cred_names: list[str]) -> bool:
            """
            Return True if the body contains an early-exit guard that references
            any of the required credential field names (e.g. `if not req.wallet_id: ...`).
            """
            for stmt in body:
                for node in _ast.walk(stmt):
                    if isinstance(node, (_ast.If,)):
                        test = node.test
                        test_src = _ast.unparse(test) if hasattr(_ast, "unparse") else ""
                        for cred in cred_names:
                            if cred in test_src:
                                # Check that the branch raises, returns, or continues
                                for sub in node.body + node.orelse:
                                    if isinstance(sub, (_ast.Raise, _ast.Return, _ast.Continue)):
                                        return True
                    if isinstance(node, (_ast.Name, _ast.Attribute)):
                        attr = node.attr if isinstance(node, _ast.Attribute) else node.id
                        if any(cred == attr for cred in cred_names):
                            # credential is at least referenced — check if it's in a guard
                            pass
            return False

        def _preceding_stmts_guard_credential(
            self, stmts: list, if_index: int, cred_names: list[str]
        ) -> bool:
            """
            Check statements BEFORE the payment if-block (in the same scope) for
            credential validation guards.
            """
            for stmt in stmts[:if_index]:
                stmt_src = _ast.unparse(stmt) if hasattr(_ast, "unparse") else ""
                for cred in cred_names:
                    if cred in stmt_src:
                        if isinstance(stmt, _ast.If):
                            for sub in stmt.body + stmt.orelse:
                                if isinstance(sub, (_ast.Raise, _ast.Return, _ast.Continue)):
                                    return True
            return False

        def _check_body(self, stmts: list):
            for idx, node in enumerate(stmts):
                if not isinstance(node, _ast.If):
                    continue

                method = self._extract_payment_method_literal(node.test)
                if method is None:
                    continue

                cred_names = PAYMENT_METHOD_CREDENTIALS[method]

                if not self._node_calls_charge(node):
                    continue

                # Check if the if-block itself guards the credential
                if self._body_guards_credential(node.body, cred_names):
                    continue

                # Check if a preceding sibling statement guards it
                if self._preceding_stmts_guard_credential(stmts, idx, cred_names):
                    continue

                # No guard found — flag it
                self.issues.append({
                    "line": node.lineno,
                    "description": (
                        f"payment_method='{method}' branch performs a charge action "
                        f"but does not validate that {cred_names} is present/non-empty "
                        f"before proceeding; a missing credential will silently skip "
                        f"the charge while leaving payment_ok=True."
                    ),
                    "severity": "critical",
                })

        def visit_FunctionDef(self, node: _ast.FunctionDef):
            self._check_body(node.body)
            self.generic_visit(node)

        visit_AsyncFunctionDef = visit_FunctionDef

        def visit_For(self, node: _ast.For):
            self._check_body(node.body)
            self.generic_visit(node)

        def visit_While(self, node: _ast.While):
            self._check_body(node.body)
            self.generic_visit(node)

    visitor = PaymentMethodVisitor()
    visitor.visit(tree)
    findings.extend(visitor.issues)
    return findings

_AUTO_PATTERNS.append(_auto_check_001)


# Added 2026-04-17 — caught after fixing: security in tools/manage_wallets.py:159
def _auto_check_002(source: str, tree: ast.AST, filepath: pathlib.Path) -> list[dict]:
    """
    A11: Monetary amount parameter not validated positive before financial mutation.

    Detects functions that accept a monetary amount parameter (e.g. amount_cents,
    price_cents) and mutate a balance/wallet field without first guarding that the
    amount is > 0.  A missing guard allows zero-amount no-ops and negative-amount
    free credits (balance_cents = current - (-500) = current + 500).
    """
    import re

    MONEY_PARAM_RE = re.compile(
        r"^(amount|amount_cents|amount_usd|price|price_cents|cost|cost_cents|"
        r"total|total_cents|charge|charge_cents|debit_cents|credit_cents)$",
        re.IGNORECASE,
    )

    FINANCIAL_NAME_RE = re.compile(
        r"(debit|credit|charge|transfer|withdraw|deposit|spend|pay|fund)",
        re.IGNORECASE,
    )

    BALANCE_KEY_RE = re.compile(r"balance|wallet|funds", re.IGNORECASE)

    def _mutates_balance(func_node: ast.FunctionDef) -> bool:
        for node in ast.walk(func_node):
            # wlt["balance_cents"] = ...  or  wallets["balance"] = ...
            if isinstance(node, ast.Assign):
                for tgt in node.targets:
                    if (
                        isinstance(tgt, ast.Subscript)
                        and isinstance(tgt.slice, ast.Constant)
                        and isinstance(tgt.slice.value, str)
                        and BALANCE_KEY_RE.search(tgt.slice.value)
                    ):
                        return True
            # balance_cents -= amount  or  balance_cents += amount
            if isinstance(node, ast.AugAssign):
                tgt = node.target
                name = (
                    tgt.id
                    if isinstance(tgt, ast.Name)
                    else (tgt.attr if isinstance(tgt, ast.Attribute) else "")
                )
                if BALANCE_KEY_RE.search(name):
                    return True
        return False

    def _has_positive_guard(func_node: ast.FunctionDef, param: str) -> bool:
        """
        Return True if one of the first 8 statements is an if/assert that
        raises or returns when param <= 0 (or param < 1, or not param > 0).
        """
        for stmt in func_node.body[:8]:
            # assert param > 0  or  assert param >= 1
            if isinstance(stmt, ast.Assert):
                test = stmt.test
                if isinstance(test, ast.Compare):
                    left = test.left
                    if isinstance(left, ast.Name) and left.id == param:
                        if any(isinstance(op, (ast.Gt, ast.GtE)) for op in test.ops):
                            return True

            if not isinstance(stmt, ast.If):
                continue

            test = stmt.test

            # if param <= 0 / if param < 1
            if isinstance(test, ast.Compare):
                left = test.left
                if isinstance(left, ast.Name) and left.id == param:
                    for op, cmp in zip(test.ops, test.comparators):
                        if isinstance(op, (ast.LtE, ast.Lt)) and isinstance(cmp, ast.Constant):
                            if cmp.value in (0, 1):
                                if any(isinstance(s, (ast.Raise, ast.Return)) for s in stmt.body):
                                    return True

            # if not (param > 0)
            if (
                isinstance(test, ast.UnaryOp)
                and isinstance(test.op, ast.Not)
                and isinstance(test.operand, ast.Compare)
            ):
                inner = test.operand
                if isinstance(inner.left, ast.Name) and inner.left.id == param:
                    if any(isinstance(op, (ast.Gt, ast.GtE)) for op in inner.ops):
                        if any(isinstance(s, (ast.Raise, ast.Return)) for s in stmt.body):
                            return True

        return False

    issues = []

    for node in ast.walk(tree):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue

        if not FINANCIAL_NAME_RE.search(node.name):
            continue

        all_args = node.args.posonlyargs + node.args.args + node.args.kwonlyargs

        for arg in all_args:
            if not MONEY_PARAM_RE.match(arg.arg):
                continue

            if _mutates_balance(node) and not _has_positive_guard(node, arg.arg):
                issues.append({
                    "line": node.lineno,
                    "description": (
                        f"Function '{node.name}' accepts monetary parameter '{arg.arg}' "
                        f"but does not validate it is > 0 before mutating wallet/balance state. "
                        f"A zero amount records a silent no-op; a negative amount inverts the "
                        f"arithmetic and credits the wallet for free."
                    ),
                    "severity": "security",
                })
                break  # one finding per function

    return issues

_AUTO_PATTERNS.append(_auto_check_002)


# Added 2026-04-17 — caught after fixing: logic_error in tools/normalize_slot.py:257
def _auto_check_003(source: str, tree: ast.AST, filepath: pathlib.Path) -> list[dict]:
    """
    Detects references to undefined names inside function bodies where a similarly-named
    parameter exists — catches typos like `hour` vs `hours_ahead`.
    """
    import ast

    issues = []

    for node in ast.walk(tree):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue

        # Collect all names defined in this function's scope:
        # parameters, local assignments, for-loop targets, with-targets, comprehension vars
        defined = set()

        # Parameters (args, vararg, kwonlyargs, kwarg, posonlyargs)
        for arg in node.args.args + node.args.posonlyargs + node.args.kwonlyargs:
            defined.add(arg.arg)
        if node.args.vararg:
            defined.add(node.args.vararg.arg)
        if node.args.kwarg:
            defined.add(node.args.kwarg.arg)

        # Walk the function body for local definitions
        for child in ast.walk(ast.Module(body=node.body, type_ignores=[])):
            if isinstance(child, ast.Assign):
                for target in child.targets:
                    if isinstance(target, ast.Name):
                        defined.add(target.id)
                    elif isinstance(target, ast.Tuple):
                        for elt in ast.walk(target):
                            if isinstance(elt, ast.Name):
                                defined.add(elt.id)
            elif isinstance(child, (ast.AnnAssign, ast.NamedExpr)):
                if isinstance(getattr(child, 'target', None), ast.Name):
                    defined.add(child.target.id)
            elif isinstance(child, ast.For):
                for elt in ast.walk(child.target):
                    if isinstance(elt, ast.Name):
                        defined.add(elt.id)
            elif isinstance(child, ast.With):
                for item in child.items:
                    if item.optional_vars and isinstance(item.optional_vars, ast.Name):
                        defined.add(item.optional_vars.id)
            elif isinstance(child, (ast.Import, ast.ImportFrom)):
                for alias in child.names:
                    defined.add(alias.asname if alias.asname else alias.name.split('.')[0])
            elif isinstance(child, (ast.ListComp, ast.SetComp, ast.GeneratorExp, ast.DictComp)):
                generators = getattr(child, 'generators', [])
                for gen in generators:
                    for elt in ast.walk(gen.target):
                        if isinstance(elt, ast.Name):
                            defined.add(elt.id)

        # Collect all Name loads in the function body (excluding the function node itself)
        for child in ast.walk(ast.Module(body=node.body, type_ignores=[])):
            if not isinstance(child, ast.Name):
                continue
            if not isinstance(child.ctx, ast.Load):
                continue

            name = child.id

            # Skip builtins, dunders, and names known to be defined
            if name in defined:
                continue
            if name.startswith('__') and name.endswith('__'):
                continue
            if name in dir(__builtins__) if isinstance(__builtins__, dict) else dir(__builtins__):
                continue

            # Only flag if there's a similarly-named defined variable (edit-distance 1 typo or
            # prefix/suffix truncation) — avoids flagging genuine globals/imports
            close_match = None
            for d in defined:
                # Exact prefix match (e.g. `hour` vs `hours_ahead`)
                if d.startswith(name) or name.startswith(d):
                    close_match = d
                    break
                # Simple one-character difference (insertion/deletion/substitution)
                if abs(len(d) - len(name)) <= 2 and (
                    name in d or d in name or
                    sum(a != b for a, b in zip(name, d)) == 1
                ):
                    close_match = d
                    break

            if close_match is None:
                continue

            issues.append({
                "line": child.col_offset if not hasattr(child, 'lineno') else child.lineno,
                "description": (
                    f"Possibly undefined name `{name}` used in `{node.name}()`; "
                    f"did you mean `{close_match}`? (NameError at runtime)"
                ),
                "severity": "high",
            })

    return issues

_AUTO_PATTERNS.append(_auto_check_003)


# Added 2026-04-17 — caught after fixing: HTTPError in tools/fetch_octo_slots.py:130
def _auto_check_004(source: str, tree: ast.AST, filepath: pathlib.Path) -> list[dict]:
    """Detect OCTO unit dicts using 'id' instead of the spec-required 'unitId' key.

    The OCTO availability API requires units to carry 'unitId', not 'id'.
    Passing 'id' silently produces a 400 HTTPError with no clear message.
    """
    results = []
    if "octo" not in filepath.stem.lower() and "octo" not in source.lower():
        return results

    for node in ast.walk(tree):
        # Look for dict literals like {"id": ..., "quantity": ...}
        if isinstance(node, ast.Dict):
            key_strings = []
            for k in node.keys:
                if isinstance(k, ast.Constant) and isinstance(k.value, str):
                    key_strings.append(k.value)
            if "id" in key_strings and "quantity" in key_strings and "unitId" not in key_strings:
                results.append({
                    "line": node.lineno,
                    "description": (
                        "Unit dict uses 'id' instead of OCTO-required 'unitId'. "
                        "The availability/booking API will return HTTP 400."
                    ),
                    "severity": "high",
                })
        # Look for dict() calls like dict(id=..., quantity=...)
        if isinstance(node, ast.Call):
            if isinstance(node.func, ast.Name) and node.func.id == "dict":
                kw_names = [kw.arg for kw in node.keywords if kw.arg is not None]
                if "id" in kw_names and "quantity" in kw_names and "unitId" not in kw_names:
                    results.append({
                        "line": node.lineno,
                        "description": (
                            "Unit dict uses 'id' instead of OCTO-required 'unitId'. "
                            "The availability/booking API will return HTTP 400."
                        ),
                        "severity": "high",
                    })
    return results

_AUTO_PATTERNS.append(_auto_check_004)
